services:
  redis:
    image: 'redis:6.0.12-alpine'
    ports:
      - '6379:6379'
    links:
      - api
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  api:
    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - .:/usr/src/app
    #  - /usr/src/app/node_modules
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:prod
    ports:
      - 4000:4000
